name: DropZone
version: ${project.version}
main: ym.dropzone.DropZonePlugin
api-version: "1.16"
folia-supported: true
softdepend:
  - ProtocolLib
  - PlaceholderAPI
commands:
  dropzone:
    aliases:
      - dz
    description: DropZone main command
permissions:
  dropzone.admin:
    default: op
  dropzone.reload:
    default: op
  dropzone.spawn:
    default: op
  dropzone.start:
    default: op
  dropzone.clear:
    default: op
  dropzone.list:
    default: op
  dropzone.debug:
    default: op
  dropzone.sync:
    default: op
  dropzone.dbstatus:
    default: op
  dropzone.outbox:
    default: op
